// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Flusher is an autogenerated mock type for the Flusher type
type Flusher struct {
	mock.Mock
}

// Flush provides a mock function with given fields: entries
func (_m *Flusher) Flush(entries [][]byte) error {
	ret := _m.Called(entries)

	var r0 error
	if rf, ok := ret.Get(0).(func([][]byte) error); ok {
		r0 = rf(entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFlusher interface {
	mock.TestingT
	Cleanup(func())
}

// NewFlusher creates a new instance of Flusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFlusher(t mockConstructorTestingTNewFlusher) *Flusher {
	mock := &Flusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
