// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.2
// source: app-instance-service.proto

package chorus

import (
	context "context"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAppInstancesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *PaginationQuery `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListAppInstancesRequest) Reset() {
	*x = ListAppInstancesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAppInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppInstancesRequest) ProtoMessage() {}

func (x *ListAppInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListAppInstancesRequest) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAppInstancesRequest) GetPagination() *PaginationQuery {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAppInstancesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*AppInstance `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *ListAppInstancesReply) Reset() {
	*x = ListAppInstancesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAppInstancesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppInstancesReply) ProtoMessage() {}

func (x *ListAppInstancesReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppInstancesReply.ProtoReflect.Descriptor instead.
func (*ListAppInstancesReply) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAppInstancesReply) GetResult() []*AppInstance {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetAppInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAppInstanceRequest) Reset() {
	*x = GetAppInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppInstanceRequest) ProtoMessage() {}

func (x *GetAppInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetAppInstanceRequest) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppInstanceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAppInstanceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppInstance *AppInstance `protobuf:"bytes,1,opt,name=appInstance,proto3" json:"appInstance,omitempty"`
}

func (x *GetAppInstanceResult) Reset() {
	*x = GetAppInstanceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppInstanceResult) ProtoMessage() {}

func (x *GetAppInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppInstanceResult.ProtoReflect.Descriptor instead.
func (*GetAppInstanceResult) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppInstanceResult) GetAppInstance() *AppInstance {
	if x != nil {
		return x.AppInstance
	}
	return nil
}

type GetAppInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *GetAppInstanceResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetAppInstanceReply) Reset() {
	*x = GetAppInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppInstanceReply) ProtoMessage() {}

func (x *GetAppInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppInstanceReply.ProtoReflect.Descriptor instead.
func (*GetAppInstanceReply) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppInstanceReply) GetResult() *GetAppInstanceResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateAppInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *CreateAppInstanceResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateAppInstanceReply) Reset() {
	*x = CreateAppInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppInstanceReply) ProtoMessage() {}

func (x *CreateAppInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppInstanceReply.ProtoReflect.Descriptor instead.
func (*CreateAppInstanceReply) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAppInstanceReply) GetResult() *CreateAppInstanceResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateAppInstanceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateAppInstanceResult) Reset() {
	*x = CreateAppInstanceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppInstanceResult) ProtoMessage() {}

func (x *CreateAppInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppInstanceResult.ProtoReflect.Descriptor instead.
func (*CreateAppInstanceResult) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAppInstanceResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAppInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppInstance *AppInstance `protobuf:"bytes,1,opt,name=appInstance,proto3" json:"appInstance,omitempty"`
}

func (x *UpdateAppInstanceRequest) Reset() {
	*x = UpdateAppInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppInstanceRequest) ProtoMessage() {}

func (x *UpdateAppInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppInstanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppInstanceRequest) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAppInstanceRequest) GetAppInstance() *AppInstance {
	if x != nil {
		return x.AppInstance
	}
	return nil
}

type UpdateAppInstanceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAppInstanceResult) Reset() {
	*x = UpdateAppInstanceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppInstanceResult) ProtoMessage() {}

func (x *UpdateAppInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppInstanceResult.ProtoReflect.Descriptor instead.
func (*UpdateAppInstanceResult) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{8}
}

type UpdateAppInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *UpdateAppInstanceResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdateAppInstanceReply) Reset() {
	*x = UpdateAppInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppInstanceReply) ProtoMessage() {}

func (x *UpdateAppInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppInstanceReply.ProtoReflect.Descriptor instead.
func (*UpdateAppInstanceReply) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAppInstanceReply) GetResult() *UpdateAppInstanceResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteAppInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAppInstanceRequest) Reset() {
	*x = DeleteAppInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppInstanceRequest) ProtoMessage() {}

func (x *DeleteAppInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppInstanceRequest) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppInstanceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAppInstanceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAppInstanceResult) Reset() {
	*x = DeleteAppInstanceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppInstanceResult) ProtoMessage() {}

func (x *DeleteAppInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppInstanceResult.ProtoReflect.Descriptor instead.
func (*DeleteAppInstanceResult) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{11}
}

type DeleteAppInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *DeleteAppInstanceResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteAppInstanceReply) Reset() {
	*x = DeleteAppInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_instance_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppInstanceReply) ProtoMessage() {}

func (x *DeleteAppInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_instance_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppInstanceReply.ProtoReflect.Descriptor instead.
func (*DeleteAppInstanceReply) Descriptor() ([]byte, []int) {
	return file_app_instance_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAppInstanceReply) GetResult() *DeleteAppInstanceResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_app_instance_service_proto protoreflect.FileDescriptor

var file_app_instance_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x70, 0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68,
	0x6f, 0x72, 0x75, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f,
	0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x61,
	0x70, 0x70, 0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x52, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x35, 0x0a, 0x0b,
	0x61, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x51, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x51,
	0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x70,
	0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x51, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x51, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x37, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xa6, 0x08, 0x0a, 0x12, 0x41, 0x70,
	0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0xc8, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x7a, 0x92, 0x41, 0x50, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x13, 0x47, 0x65, 0x74, 0x20, 0x61, 0x6e,
	0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x25, 0x54,
	0x68, 0x69, 0x73, 0x20, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x20, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x70, 0x2d, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0xd0, 0x01, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x1f, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70,
	0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x7c, 0x92, 0x41, 0x57, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x20,
	0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0x2d, 0x54,
	0x68, 0x69, 0x73, 0x20, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x20, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x73, 0x20, 0x61, 0x20, 0x6c, 0x69, 0x73, 0x74, 0x20, 0x6f, 0x66, 0x20, 0x61,
	0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x70, 0x70, 0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0xc5,
	0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x41, 0x70,
	0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x1e, 0x2e, 0x63, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x7b, 0x92, 0x41, 0x53, 0x0a, 0x12,
	0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x70,
	0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x25, 0x54, 0x68, 0x69, 0x73,
	0x20, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x20, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01, 0x2a, 0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x70, 0x2d, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0xd2, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x2e, 0x63,
	0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70,
	0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x7b,
	0x92, 0x41, 0x53, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x20,
	0x61, 0x6e, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a,
	0x25, 0x54, 0x68, 0x69, 0x73, 0x20, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x20, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01, 0x2a, 0x1a,
	0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70,
	0x70, 0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0xd4, 0x01, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x20, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x7d, 0x92, 0x41, 0x53, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x1a, 0x25, 0x54, 0x68, 0x69, 0x73, 0x20, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x20, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61,
	0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x21, 0x2a, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x70, 0x70, 0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x42, 0xba, 0x01, 0x92, 0x41, 0xac, 0x01, 0x12, 0x82, 0x01, 0x0a, 0x1b, 0x63, 0x68,
	0x6f, 0x72, 0x75, 0x73, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x5e, 0x0a, 0x1b, 0x63, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x20, 0x61, 0x70, 0x70, 0x20, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a,
	0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x48, 0x4f,
	0x52, 0x55, 0x53, 0x2d, 0x54, 0x52, 0x45, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2d, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x1a, 0x11, 0x64, 0x65, 0x76, 0x40, 0x63, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2d, 0x74, 0x72, 0x65, 0x2e, 0x63, 0x68, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x2a, 0x01,
	0x01, 0x32, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a,
	0x73, 0x6f, 0x6e, 0x3a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_instance_service_proto_rawDescOnce sync.Once
	file_app_instance_service_proto_rawDescData = file_app_instance_service_proto_rawDesc
)

func file_app_instance_service_proto_rawDescGZIP() []byte {
	file_app_instance_service_proto_rawDescOnce.Do(func() {
		file_app_instance_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_instance_service_proto_rawDescData)
	})
	return file_app_instance_service_proto_rawDescData
}

var file_app_instance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_instance_service_proto_goTypes = []interface{}{
	(*ListAppInstancesRequest)(nil),  // 0: chorus.ListAppInstancesRequest
	(*ListAppInstancesReply)(nil),    // 1: chorus.ListAppInstancesReply
	(*GetAppInstanceRequest)(nil),    // 2: chorus.GetAppInstanceRequest
	(*GetAppInstanceResult)(nil),     // 3: chorus.GetAppInstanceResult
	(*GetAppInstanceReply)(nil),      // 4: chorus.GetAppInstanceReply
	(*CreateAppInstanceReply)(nil),   // 5: chorus.CreateAppInstanceReply
	(*CreateAppInstanceResult)(nil),  // 6: chorus.CreateAppInstanceResult
	(*UpdateAppInstanceRequest)(nil), // 7: chorus.UpdateAppInstanceRequest
	(*UpdateAppInstanceResult)(nil),  // 8: chorus.UpdateAppInstanceResult
	(*UpdateAppInstanceReply)(nil),   // 9: chorus.UpdateAppInstanceReply
	(*DeleteAppInstanceRequest)(nil), // 10: chorus.DeleteAppInstanceRequest
	(*DeleteAppInstanceResult)(nil),  // 11: chorus.DeleteAppInstanceResult
	(*DeleteAppInstanceReply)(nil),   // 12: chorus.DeleteAppInstanceReply
	(*PaginationQuery)(nil),          // 13: chorus.PaginationQuery
	(*AppInstance)(nil),              // 14: chorus.AppInstance
}
var file_app_instance_service_proto_depIdxs = []int32{
	13, // 0: chorus.ListAppInstancesRequest.pagination:type_name -> chorus.PaginationQuery
	14, // 1: chorus.ListAppInstancesReply.result:type_name -> chorus.AppInstance
	14, // 2: chorus.GetAppInstanceResult.appInstance:type_name -> chorus.AppInstance
	3,  // 3: chorus.GetAppInstanceReply.result:type_name -> chorus.GetAppInstanceResult
	6,  // 4: chorus.CreateAppInstanceReply.result:type_name -> chorus.CreateAppInstanceResult
	14, // 5: chorus.UpdateAppInstanceRequest.appInstance:type_name -> chorus.AppInstance
	8,  // 6: chorus.UpdateAppInstanceReply.result:type_name -> chorus.UpdateAppInstanceResult
	11, // 7: chorus.DeleteAppInstanceReply.result:type_name -> chorus.DeleteAppInstanceResult
	2,  // 8: chorus.AppInstanceService.GetAppInstance:input_type -> chorus.GetAppInstanceRequest
	0,  // 9: chorus.AppInstanceService.ListAppInstances:input_type -> chorus.ListAppInstancesRequest
	14, // 10: chorus.AppInstanceService.CreateAppInstance:input_type -> chorus.AppInstance
	7,  // 11: chorus.AppInstanceService.UpdateAppInstance:input_type -> chorus.UpdateAppInstanceRequest
	10, // 12: chorus.AppInstanceService.DeleteAppInstance:input_type -> chorus.DeleteAppInstanceRequest
	4,  // 13: chorus.AppInstanceService.GetAppInstance:output_type -> chorus.GetAppInstanceReply
	1,  // 14: chorus.AppInstanceService.ListAppInstances:output_type -> chorus.ListAppInstancesReply
	5,  // 15: chorus.AppInstanceService.CreateAppInstance:output_type -> chorus.CreateAppInstanceReply
	9,  // 16: chorus.AppInstanceService.UpdateAppInstance:output_type -> chorus.UpdateAppInstanceReply
	12, // 17: chorus.AppInstanceService.DeleteAppInstance:output_type -> chorus.DeleteAppInstanceReply
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_app_instance_service_proto_init() }
func file_app_instance_service_proto_init() {
	if File_app_instance_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_app_instance_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_instance_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAppInstancesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAppInstancesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppInstanceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppInstanceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAppInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAppInstanceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAppInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppInstanceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_instance_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_instance_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_instance_service_proto_goTypes,
		DependencyIndexes: file_app_instance_service_proto_depIdxs,
		MessageInfos:      file_app_instance_service_proto_msgTypes,
	}.Build()
	File_app_instance_service_proto = out.File
	file_app_instance_service_proto_rawDesc = nil
	file_app_instance_service_proto_goTypes = nil
	file_app_instance_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppInstanceServiceClient is the client API for AppInstanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppInstanceServiceClient interface {
	GetAppInstance(ctx context.Context, in *GetAppInstanceRequest, opts ...grpc.CallOption) (*GetAppInstanceReply, error)
	ListAppInstances(ctx context.Context, in *ListAppInstancesRequest, opts ...grpc.CallOption) (*ListAppInstancesReply, error)
	CreateAppInstance(ctx context.Context, in *AppInstance, opts ...grpc.CallOption) (*CreateAppInstanceReply, error)
	UpdateAppInstance(ctx context.Context, in *UpdateAppInstanceRequest, opts ...grpc.CallOption) (*UpdateAppInstanceReply, error)
	DeleteAppInstance(ctx context.Context, in *DeleteAppInstanceRequest, opts ...grpc.CallOption) (*DeleteAppInstanceReply, error)
}

type appInstanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppInstanceServiceClient(cc grpc.ClientConnInterface) AppInstanceServiceClient {
	return &appInstanceServiceClient{cc}
}

func (c *appInstanceServiceClient) GetAppInstance(ctx context.Context, in *GetAppInstanceRequest, opts ...grpc.CallOption) (*GetAppInstanceReply, error) {
	out := new(GetAppInstanceReply)
	err := c.cc.Invoke(ctx, "/chorus.AppInstanceService/GetAppInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstanceServiceClient) ListAppInstances(ctx context.Context, in *ListAppInstancesRequest, opts ...grpc.CallOption) (*ListAppInstancesReply, error) {
	out := new(ListAppInstancesReply)
	err := c.cc.Invoke(ctx, "/chorus.AppInstanceService/ListAppInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstanceServiceClient) CreateAppInstance(ctx context.Context, in *AppInstance, opts ...grpc.CallOption) (*CreateAppInstanceReply, error) {
	out := new(CreateAppInstanceReply)
	err := c.cc.Invoke(ctx, "/chorus.AppInstanceService/CreateAppInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstanceServiceClient) UpdateAppInstance(ctx context.Context, in *UpdateAppInstanceRequest, opts ...grpc.CallOption) (*UpdateAppInstanceReply, error) {
	out := new(UpdateAppInstanceReply)
	err := c.cc.Invoke(ctx, "/chorus.AppInstanceService/UpdateAppInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstanceServiceClient) DeleteAppInstance(ctx context.Context, in *DeleteAppInstanceRequest, opts ...grpc.CallOption) (*DeleteAppInstanceReply, error) {
	out := new(DeleteAppInstanceReply)
	err := c.cc.Invoke(ctx, "/chorus.AppInstanceService/DeleteAppInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppInstanceServiceServer is the server API for AppInstanceService service.
type AppInstanceServiceServer interface {
	GetAppInstance(context.Context, *GetAppInstanceRequest) (*GetAppInstanceReply, error)
	ListAppInstances(context.Context, *ListAppInstancesRequest) (*ListAppInstancesReply, error)
	CreateAppInstance(context.Context, *AppInstance) (*CreateAppInstanceReply, error)
	UpdateAppInstance(context.Context, *UpdateAppInstanceRequest) (*UpdateAppInstanceReply, error)
	DeleteAppInstance(context.Context, *DeleteAppInstanceRequest) (*DeleteAppInstanceReply, error)
}

// UnimplementedAppInstanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAppInstanceServiceServer struct {
}

func (*UnimplementedAppInstanceServiceServer) GetAppInstance(context.Context, *GetAppInstanceRequest) (*GetAppInstanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppInstance not implemented")
}
func (*UnimplementedAppInstanceServiceServer) ListAppInstances(context.Context, *ListAppInstancesRequest) (*ListAppInstancesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAppInstances not implemented")
}
func (*UnimplementedAppInstanceServiceServer) CreateAppInstance(context.Context, *AppInstance) (*CreateAppInstanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppInstance not implemented")
}
func (*UnimplementedAppInstanceServiceServer) UpdateAppInstance(context.Context, *UpdateAppInstanceRequest) (*UpdateAppInstanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAppInstance not implemented")
}
func (*UnimplementedAppInstanceServiceServer) DeleteAppInstance(context.Context, *DeleteAppInstanceRequest) (*DeleteAppInstanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAppInstance not implemented")
}

func RegisterAppInstanceServiceServer(s *grpc.Server, srv AppInstanceServiceServer) {
	s.RegisterService(&_AppInstanceService_serviceDesc, srv)
}

func _AppInstanceService_GetAppInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstanceServiceServer).GetAppInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chorus.AppInstanceService/GetAppInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstanceServiceServer).GetAppInstance(ctx, req.(*GetAppInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstanceService_ListAppInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstanceServiceServer).ListAppInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chorus.AppInstanceService/ListAppInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstanceServiceServer).ListAppInstances(ctx, req.(*ListAppInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstanceService_CreateAppInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstanceServiceServer).CreateAppInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chorus.AppInstanceService/CreateAppInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstanceServiceServer).CreateAppInstance(ctx, req.(*AppInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstanceService_UpdateAppInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstanceServiceServer).UpdateAppInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chorus.AppInstanceService/UpdateAppInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstanceServiceServer).UpdateAppInstance(ctx, req.(*UpdateAppInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstanceService_DeleteAppInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstanceServiceServer).DeleteAppInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chorus.AppInstanceService/DeleteAppInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstanceServiceServer).DeleteAppInstance(ctx, req.(*DeleteAppInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppInstanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chorus.AppInstanceService",
	HandlerType: (*AppInstanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppInstance",
			Handler:    _AppInstanceService_GetAppInstance_Handler,
		},
		{
			MethodName: "ListAppInstances",
			Handler:    _AppInstanceService_ListAppInstances_Handler,
		},
		{
			MethodName: "CreateAppInstance",
			Handler:    _AppInstanceService_CreateAppInstance_Handler,
		},
		{
			MethodName: "UpdateAppInstance",
			Handler:    _AppInstanceService_UpdateAppInstance_Handler,
		},
		{
			MethodName: "DeleteAppInstance",
			Handler:    _AppInstanceService_DeleteAppInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app-instance-service.proto",
}
