// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.2
// source: cursor.proto

package chorus

import (
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Base64-encoded string representing the current window of data
	CurrentPage string `protobuf:"bytes,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	// The page to request, w.r.t the current page.
	// Can be one of `FIRST`, `PREVIOUS`, `NEXT`, `LAST`
	PageRequest string `protobuf:"bytes,2,opt,name=pageRequest,proto3" json:"pageRequest,omitempty"`
	// The size of the page requested. The handling service should impose a hard limit on this
	PageSize uint64 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *RequestCursor) Reset() {
	*x = RequestCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cursor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCursor) ProtoMessage() {}

func (x *RequestCursor) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCursor.ProtoReflect.Descriptor instead.
func (*RequestCursor) Descriptor() ([]byte, []int) {
	return file_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCursor) GetCurrentPage() string {
	if x != nil {
		return x.CurrentPage
	}
	return ""
}

func (x *RequestCursor) GetPageRequest() string {
	if x != nil {
		return x.PageRequest
	}
	return ""
}

func (x *RequestCursor) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ResponseCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Base64-encoded string representing the current window of data
	CurrentPage string `protobuf:"bytes,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	// Hints for UI to display whether a previous and/or next page of data
	// are available.
	HasPrevious bool `protobuf:"varint,2,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	HasNext     bool `protobuf:"varint,3,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
}

func (x *ResponseCursor) Reset() {
	*x = ResponseCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cursor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCursor) ProtoMessage() {}

func (x *ResponseCursor) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCursor.ProtoReflect.Descriptor instead.
func (*ResponseCursor) Descriptor() ([]byte, []int) {
	return file_cursor_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseCursor) GetCurrentPage() string {
	if x != nil {
		return x.CurrentPage
	}
	return ""
}

func (x *ResponseCursor) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *ResponseCursor) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

var File_cursor_proto protoreflect.FileDescriptor

var file_cursor_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6e, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x68, 0x61, 0x73, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x68,
	0x6f, 0x72, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cursor_proto_rawDescOnce sync.Once
	file_cursor_proto_rawDescData = file_cursor_proto_rawDesc
)

func file_cursor_proto_rawDescGZIP() []byte {
	file_cursor_proto_rawDescOnce.Do(func() {
		file_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(file_cursor_proto_rawDescData)
	})
	return file_cursor_proto_rawDescData
}

var file_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cursor_proto_goTypes = []interface{}{
	(*RequestCursor)(nil),  // 0: chorus.RequestCursor
	(*ResponseCursor)(nil), // 1: chorus.ResponseCursor
}
var file_cursor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cursor_proto_init() }
func file_cursor_proto_init() {
	if File_cursor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cursor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cursor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cursor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_proto_goTypes,
		DependencyIndexes: file_cursor_proto_depIdxs,
		MessageInfos:      file_cursor_proto_msgTypes,
	}.Build()
	File_cursor_proto = out.File
	file_cursor_proto_rawDesc = nil
	file_cursor_proto_goTypes = nil
	file_cursor_proto_depIdxs = nil
}
