swagger: "2.0"
info:
  title: chorus authentication service
  version: "1.0"
  contact:
    name: chorus authentication service
    url: https://github.com/CHORUS-TRE/chorus-backend
    email: dev@chorus-tre.ch
tags:
  - name: AuthenticationService
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/rest/v1/authentication/login:
    post:
      summary: Authenticate
      description: This endpoint authenticates a user
      operationId: AuthenticationService_Authenticate
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusAuthenticationReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/chorusCredentials'
      tags:
        - AuthenticationService
      security: []
  /api/rest/v1/authentication/oauth2/{id}/login:
    get:
      summary: Authenticate using Auth 2.0
      description: This endpoint redirects a user to a configured oauth2 provider
      operationId: AuthenticationService_AuthenticateOauth
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusAuthenticateOauthReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - AuthenticationService
      security: []
  /api/rest/v1/authentication/oauth2/{id}/redirect:
    get:
      summary: Authenticate redirect using Auth 2.0
      description: This endpoint is called by the provider after auth for the backend to retrieve the user profile
      operationId: AuthenticationService_AuthenticateOauthRedirect
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusAuthenticateOauthRedirectReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: state
          in: query
          required: false
          type: string
        - name: sessionState
          in: query
          required: false
          type: string
        - name: code
          in: query
          required: false
          type: string
      tags:
        - AuthenticationService
      security: []
definitions:
  chorusAuthenticateOauthRedirectReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusAuthenticateOauthRedirectResult'
  chorusAuthenticateOauthRedirectResult:
    type: object
    properties:
      token:
        type: string
  chorusAuthenticateOauthReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusAuthenticateOauthResult'
  chorusAuthenticateOauthResult:
    type: object
    properties:
      redirectURI:
        type: string
  chorusAuthenticationReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusAuthenticationResult'
  chorusAuthenticationResult:
    type: object
    properties:
      token:
        type: string
  chorusCredentials:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      totp:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
